version: 0.1

phases:
  build:
    commands:
      - apt install spatialite-bin
      - apt install libsqlite3-mod-spatialite
      - apt install mdbtools
      - mkdir -p build/python/lib/3.6/site-packages
      - pipenv -v --python 3.6
      - pipenv run pip install -r requirements.txt --target build/python/lib/3.6/site-packages
  post_build:
    commands:
      - python3 run.py
artifacts:
  files:
      - dataset/**/*
      - fuentes/**/*
