version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo "$S3_BUCKET_TARGET"
      - aws s3 sync "$S3_BUCKET_TARGET" ./dataset
  build:
    commands:
      - apt install -y spatialite-bin
      - apt install -y libsqlite3-mod-spatialite
      - apt install -y mdbtools
      #- mkdir -p build/python/lib/3.6/site-packages
      - pipenv -v --python 3.6
      - pipenv run pip install -r requirements.txt
      # --target build/python/lib/3.6/site-packages
  post_build:
    commands:
      - pipenv run python3 run.py
      - aws s3 sync ./dataset "$S3_BUCKET_TARGET"
# artifacts:
#   files:
#       - dataset/**/*
#       - fuentes/**/*
