create table DST_PROVINCIAS (
  A TEXT,
  B TEXT,
  crs REAL,
  PRIMARY KEY (A, B),
  FOREIGN KEY(A) REFERENCES PROVINCIAS(ID),
  FOREIGN KEY(B) REFERENCES PROVINCIAS(ID)
);
create table DST_MUNICIPIOS (
  A TEXT,
  B TEXT,
  crs REAL,
  PRIMARY KEY (A, B),
  FOREIGN KEY(A) REFERENCES MUNICIPIOS(ID),
  FOREIGN KEY(B) REFERENCES MUNICIPIOS(ID)
);
