create table AEMET_MES (
  BASE TEXT,
  FECHA TEXT,
  "e" INTEGER,
"hr" INTEGER,
"np_001" INTEGER,
"np_010" INTEGER,
"np_100" INTEGER,
"np_300" INTEGER,
"nt_00" INTEGER,
"nt_30" INTEGER,
"nw_55" INTEGER,
"nw_91" INTEGER,
"p_sol" INTEGER,
"w_med" INTEGER,
"w_rec" INTEGER,
"ta_max" TEXT,
"w_racha" TEXT,
"ta_min" TEXT,
"q_max" TEXT,
"q_min" TEXT,
"p_max" TEXT,
"p_mes" REAL,
"tm_min" REAL,
"ti_max" REAL,
"inso" REAL,
"q_med" REAL,
"tm_mes" REAL,
"ts_min" REAL,
"tm_max" REAL,
"q_mar" REAL,
  PRIMARY KEY (BASE, FECHA),
  FOREIGN KEY(BASE) REFERENCES AEMET_BASES(ID)
)